### ISSUE TITLE
Continual 'Changed' events in droid even when no property is changed.

### ISSUE THREAD

**Issue by tlhintoq** [jamesmontemagno/BatteryPlugin#1]
From a Visual Studio perspective... The `BatteryChangedEventArgs e` has no changed properties between events. Yet is being raised every quarter second or so.  I'm going to have to filter this before actually throwing an event to the rest of my program. So...
1) It would be nice if the plugin didn't hammer false change events.
2) It would be nice if the 'equals' operator comparred values of the object instead of instance so we can see if two different event args are equal to each other.

**Comment by jamesmontemagno** [comment]
What device or simulator are you actually testing on?

**Comment by tlhintoq** [comment]
Samsung tab4 and Samsung s2 both are exhibiting this behavior.

**Comment by jamesmontemagno** [comment]
Can you try: https://www.nuget.org/packages/Xam.Plugin.Battery/2.0.1-beta13

**Comment by tlhintoq** [comment]
Shall do - First thing in the morning when I am at the office.
Thanks for the fast attention to this!

**Comment by tlhintoq** [comment]
Works like a charm.  When I launch the app I make a programmatic call to get the status at launch, just so the UI doesn't sit there looking broken until the first event is fired by the device.  After that I've only seen events thrown for dropped level and plug/unplug from charger; exactly as one would expect.

I've beat on it for an hour now, letting it discharge, plug in to AC... plug in to USB... All the eventargs properties are perfect and I haven't seen any no-change false event.

**Thank you again for such swift response!**

**Comment by jamesmontemagno** [comment]
YAY :)
Will push on production package.
