### ISSUE TITLE
[UWP] Always report 'Full' when is not

### ISSUE THREAD

**Issue by farlop** [jamesmontemagno/BatteryPlugin#3]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.1.0
Device Tested On: Windows 10 (PC & Mobile)

### Expected Behavior
Should not be Full if the percentage is less than 100% (Charging or discharging...)

### Actual Behavior
Always reports Full, due to the wrong IF condition in line 92:

` if (percentage >= 1.0)`

it should be >=100, as percentage is 0-100

**Comment by Englund0110** [comment]
Anything new on this issue?

**Comment by jamesmontemagno** [comment]
PUshing out 2.1.1
