### ISSUE TITLE
Simulate battery level change

### ISSUE THREAD

**Issue by ilannt** [jamesmontemagno/BatteryPlugin#6]
How can I simulate a battery level change in the emulator to test my BatteryChanged handler?

thank you

--ilann

**Comment by jamesmontemagno** [comment]
Depends on if the emulator supports it. If it does then you will get the change events.

**Comment by ilannt** [comment]
I'm using the visual studio 2017 emulator, but can I simulate a battery level change programmatically in a timer for example?
