### ISSUE TITLE
Plugin can be used in VS 2017 - C#?

### ISSUE THREAD

**Issue by digitaico** [jamesmontemagno/BatteryPlugin#9]
HI,  I'd like to know if this plugin can be used in VisualStudio 2017,  C#, >NET 4.6.  for a Windows 10 desktop app.  classic windows, not UWA.

Thanks,

**Comment by jamesmontemagno** [comment]
not currently, i have the list of supported platforms. It is an interface and you can implement it though.

**Comment by digitaico** [comment]
Thanks,
